let store = {
  _state: {
    posters: {
      posts: [
        {
          id: 1,
          name: "Кино один",
          top: 5,
          image: "evakuaciya.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
        {
          id: 2,
          name: "Кино 2",
          top: 5,
          image: "feya.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
        {
          id: 3,
          name: "Кино 3",
          top: 5,
          image: "kanikuly_v_afrike.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
        {
          id: 4,
          name: "Кино 4",
          top: 5,
          image: "komnata_zhelaniy.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
        {
          id: 5,
          name: "Кино 5",
          top: 5,
          image: "krasnye_tufelki.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
        {
          id: 6,
          name: "Кино 6",
          top: 5,
          image: "perevodchiki.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
        {
          id: 7,
          name: "Кино 7",
          top: 5,
          image: "presledovanie.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
        {
          id: 8,
          name: "Кино 8",
          top: 5,
          image: "viking_vik.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
        {
          id: 9,
          name: "Кино 9",
          top: 5,
          image: "presledovanie.jpg",
          description: "Laborum dolore cupidatat amet sint.",
          release: 2016,
          country: "Россия",
          genre: "Комедия",
          quality: 720,
          translation: "Русский",
          duration: 90,
          Premiere: 2021,
          message: "Hi, how are you?",
          likesCount: 12,
        },
      ],
      dialogs: [
        { id: 1, name: "Dimych" },
        { id: 2, name: "Andreq" },
        { id: 3, name: "Sveta" },
        { id: 4, name: "Viktor" },
        { id: 5, name: "Sasha" },
        { id: 6, name: "Valera" },
      ],
    },
  },
};

window.store = store;
export default store;
